### ISSUE TITLE
Crash on `babel-eslint`

### ISSUE THREAD

**Issue by fisker** [futpib/eslint-template-visitor#14]
I don't know which rule use it, possible from `eslint-plugin-unicorn`, it can't find [`visitorKeys`](https://github.com/futpib/eslint-template-visitor/blob/de46f08e21393b5bdbd81f5a40b9ee9f95a0c3a0/lib/match-keys.js#L27) for `{type: "Import"}`.

Stack

```text
Occurred while linting <CWD>\__tests__\methods.js:23
    at <CWD>\node_modules\eslint-template-visitor\lib\match-keys.js:26:55
    at Array.filter (<anonymous>)
    at getMatchKeys (<CWD>\node_modules\eslint-template-visitor\lib\match-keys.js:26:26)
    at TemplateManager._nodeMatches (<CWD>\node_modules\eslint-template-visitor\lib\index.js:201:41)
    at TemplateManager._nodePropertyMatches (<CWD>\node_modules\eslint-template-visitor\lib\index.js:229:15)
    at <CWD>\node_modules\eslint-template-visitor\lib\index.js:204:16
    at Array.every (<anonymous>)
    at TemplateManager._nodeMatches (<CWD>\node_modules\eslint-template-visitor\lib\index.js:203:31)
    at TemplateManager._nodePropertyMatches (<CWD>\node_modules\eslint-template-visitor\lib\index.js:229:15)
    at <CWD>\node_modules\eslint-template-visitor\lib\index.js:204:16
error Command failed with exit code 2.
```

**Comment by futpib** [comment]
Can you provide a way to reproduce this or at least the code that was linted and the parser used?

**Comment by fisker** [comment]
Parser is `babel-eslint`, wrote in title.

I'll need more time to figure how to reproduce

**Comment by fisker** [comment]
I forgot what's the context, and `babel-eslint` is outdated, let's close this.
